language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
install:
  - npm install -g firebase-tools
branches:
  only:
  - develop
script:
  - npm install -g @vue/cli
  - npm install
  - npm run lint
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --project luxtraveldevelop
