language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
install:
  - npm install -g firebase-tools
  - npm install -g @vue/cli
branches:
  only:
  - develop
  script:
  - npm install
  # - npm run lint
  # - npm run test
  - unset CI
  - npm run build
  after_success:
  - firebase deploy --token $FIREBASE_TOKEN --project reactnewbie
  # env:
  #   global:
  #   - REACT_APP_BASE_API: $REACT_APP_BASE_API
